// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4-AfuZeiNZ2mDryK14BRUaFjLuHVy4A',
    appId: '1:740286725484:web:5e48e23661d17cf2818749',
    messagingSenderId: '740286725484',
    projectId: 'agir-vite-v2',
    authDomain: 'agir-vite-v2.firebaseapp.com',
    storageBucket: 'agir-vite-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6riNF9Glt6e36q0_jsk0bGV1spB_tFU',
    appId: '1:740286725484:android:567e84d95478fb1a818749',
    messagingSenderId: '740286725484',
    projectId: 'agir-vite-v2',
    storageBucket: 'agir-vite-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKLjD7PqsKUA0TouyN4gWqjjy74XPxfI',
    appId: '1:740286725484:ios:fdae999bffb27fb6818749',
    messagingSenderId: '740286725484',
    projectId: 'agir-vite-v2',
    storageBucket: 'agir-vite-v2.firebasestorage.app',
    iosBundleId: 'com.avcespoir.agirVite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKLjD7PqsKUA0TouyN4gWqjjy74XPxfI',
    appId: '1:740286725484:ios:fdae999bffb27fb6818749',
    messagingSenderId: '740286725484',
    projectId: 'agir-vite-v2',
    storageBucket: 'agir-vite-v2.firebasestorage.app',
    iosBundleId: 'com.avcespoir.agirVite',
  );
}
